apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql-cluster.yaml

  - redis.yaml


  - celery-worker.yaml


images:
  - name: background-job-tracker
    newName: background-job-tracker
    newTag: latest
