apiVersion: v1
kind: Secret
metadata:
  name: background-job-tracker-pg-credentials
type: kubernetes.io/basic-auth
stringData:
  username: background-job-tracker_user
  password: changeme

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: background-job-tracker-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 10Gi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: background-job-tracker_db
      owner: background-job-tracker_user
      secret:
        name: background-job-tracker-pg-credentials

  monitoring:
    enablePodMonitor: true
