apiVersion: v1
kind: Secret
metadata:
  name: background-job-tracker-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-this-to-a-random-secret-key-in-production"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  SENTRY_DSN: ""
