apiVersion: v1
kind: Service
metadata:
  name: background-job-tracker-web
  labels:
    app: background-job-tracker
    component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: background-job-tracker
    component: web
