# Generated by Django 6.0.8 on 2026-08-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("projects", "0005_alter_apikey_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("FAILURE_RATE", "Failure Rate"),
                            ("RETRY_RATE", "Retry Rate"),
                            ("P95_DURATION", "P95 Duration"),
                        ],
                        max_length=20,
                        verbose_name="metric",
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        help_text="Percentage (0-100) for rates, milliseconds for duration.",
                        verbose_name="threshold",
                    ),
                ),
                (
                    "window_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Time window to evaluate the metric over.",
                        verbose_name="window minutes",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("DEGRADED", "Degraded"), ("CRITICAL", "Critical")],
                        default="DEGRADED",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "alert rule",
                "verbose_name_plural": "alert rules",
                "ordering": ["-created_at"],
            },
        ),
    ]
