# Generated by Django 6.0.8 on 2026-08-21 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="window_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Evaluation time window (e.g., last 60 minutes)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
                verbose_name="window in minutes",
            ),
        ),
    ]
