# Generated by Django 6.0.8 on 2026-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_alter_alertrule_window_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="metric",
            field=models.CharField(
                choices=[
                    ("FAILURE_RATE", "Failure Rate"),
                    ("RETRY_RATE", "Retry Rate"),
                    ("P95_DURATION", "P95 Duration"),
                    ("MISSED_EXECUTION", "Missed Execution"),
                    ("STALLED_EXECUTION", "Stalled Execution"),
                    ("OVERDUE_EXECUTION", "Overdue Execution"),
                ],
                max_length=20,
                verbose_name="metric",
            ),
        ),
    ]
