# Generated by Django 6.0.8 on 2026-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alter_alertrule_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="metric",
            field=models.CharField(
                choices=[
                    ("FAILURE_RATE", "Failure Rate"),
                    ("RETRY_RATE", "Retry Rate"),
                    ("P95_DURATION", "P95 Duration"),
                    ("MISSED_EXECUTION", "Missed Execution"),
                    ("STALLED_EXECUTION", "Stalled Execution"),
                    ("OVERDUE_EXECUTION", "Overdue Execution"),
                    ("FAILURE_RATE_ANOMALY", "Failure Rate Anomaly"),
                    ("RETRY_RATE_ANOMALY", "Retry Rate Anomaly"),
                    ("DURATION_ANOMALY", "Duration Anomaly"),
                    ("EXECUTION_VOLUME_ANOMALY", "Execution Volume Anomaly"),
                ],
                max_length=30,
                verbose_name="metric",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="threshold",
            field=models.FloatField(
                default=0.0,
                help_text="Percentage (0-100) for rates, milliseconds for duration. Ignored for anomaly alerts.",
                verbose_name="threshold",
            ),
        ),
    ]
