# Generated by Django 6.0.8 on 2026-08-19 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("team", "name"),
                name="unique_active_project_name_per_team",
            ),
        ),
    ]
