# Generated by Django 6.0.8 on 2026-08-20 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_apikey_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
            },
        ),
    ]
