# Generated by Django 6.0.8 on 2026-08-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0001_initial"),
        ("jobs", "0001_initial"),
        ("projects", "0005_alter_apikey_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="execution",
            name="unique_execution_external_id_per_job",
        ),
        migrations.AddField(
            model_name="execution",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="projects.project",
                verbose_name="project",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("project", "external_id"),
                name="unique_execution_external_id_per_project",
            ),
        ),
    ]
