# Generated by Django 6.0.8 on 2026-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "executions",
            "0002_remove_execution_unique_execution_external_id_per_job_and_more",
        ),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="execution",
            name="unique_execution_external_id_per_project",
        ),
        migrations.AddField(
            model_name="execution",
            name="last_event_at",
            field=models.DateTimeField(null=True, verbose_name="last event at"),
        ),
        migrations.AlterField(
            model_name="execution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="execution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(
                fields=("job", "external_id"),
                name="unique_execution_external_id_per_job",
            ),
        ),
        migrations.RemoveField(
            model_name="execution",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="execution",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="execution",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="execution",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="execution",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="execution",
            name="project",
        ),
    ]
