# Generated by Django 6.0.8 on 2026-08-20 07:29

from django.db import migrations
from django.db.models import F


def backfill_last_event_at(apps, schema_editor):
    Execution = apps.get_model("executions", "Execution")
    Execution.objects.update(last_event_at=F("created_at"))


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "executions",
            "0003_remove_execution_unique_execution_external_id_per_project_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(backfill_last_event_at, reverse_backfill),
    ]
