# Generated by Django 6.0.8 on 2026-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0004_backfill_last_event_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="last_event_at",
            field=models.DateTimeField(verbose_name="last event at"),
        ),
    ]
