# Generated by Django 6.0.8 on 2026-08-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0005_alter_execution_last_event_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, verbose_name="event ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "event_timestamp",
                    models.DateTimeField(verbose_name="event timestamp"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finished at"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="duration in ms"),
                ),
                (
                    "queue",
                    models.CharField(blank=True, max_length=255, verbose_name="queue"),
                ),
                (
                    "worker",
                    models.CharField(blank=True, max_length=255, verbose_name="worker"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="retry count"),
                ),
                (
                    "error_type",
                    models.CharField(blank=True, max_length=255, verbose_name="error type"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                ("traceback", models.TextField(blank=True, verbose_name="traceback")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="executions.execution",
                        verbose_name="execution",
                    ),
                ),
            ],
            options={
                "verbose_name": "execution event",
                "verbose_name_plural": "execution events",
                "ordering": ["-event_timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["execution", "-event_timestamp"],
                        name="executions__executi_307309_idx",
                    ),
                    models.Index(
                        fields=["event_timestamp"],
                        name="executions__event_t_00c414_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution", "event_id"),
                        name="unique_event_id_per_execution",
                    )
                ],
            },
        ),
    ]
