# Generated by Django 6.0.8 on 2026-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0006_executionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="framework",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="framework"
            ),
        ),
        migrations.AddField(
            model_name="executionevent",
            name="framework",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="framework"
            ),
        ),
    ]
