# Generated by Django 6.0.8 on 2026-09-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executions", "0007_execution_framework_executionevent_framework"),
        ("jobs", "0003_alter_job_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(fields=["job", "-started_at"], name="executions__job_id_ad4125_idx"),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(fields=["job", "status"], name="executions__job_id_91d2e4_idx"),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(fields=["created_at"], name="executions__created_0d48d3_idx"),
        ),
    ]
