# Generated by Django 6.0.8 on 2026-08-20 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0005_alter_apikey_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, verbose_name="job name")),
                (
                    "task_identifier",
                    models.CharField(max_length=255, verbose_name="task identifier"),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("verified", "Verified"), ("unverified", "Unverified")],
                        default="unverified",
                        max_length=20,
                        verbose_name="verification status",
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last verified at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("project", "task_identifier"),
                        name="unique_active_job_task_identifier_per_project",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_identifier",
                    models.CharField(max_length=255, verbose_name="task identifier"),
                ),
                (
                    "task_name",
                    models.CharField(blank=True, max_length=255, verbose_name="task name"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="first seen at"),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True, verbose_name="last seen at")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_registries",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "task registry entry",
                "verbose_name_plural": "task registry entries",
                "ordering": ["-last_seen_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "task_identifier"),
                        name="unique_task_registry_per_project",
                    )
                ],
            },
        ),
    ]
