# Generated by Django 6.0.8 on 2026-08-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("disabled", "Disabled"),
                ],
                default="active",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
