apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

# Production-specific configurations
replicas:
  - name: background-job-tracker-web
    count: 3

  - name: background-job-tracker-celery-worker
    count: 2


# Production-specific patches
patches:
  - target:
      kind: Deployment
      name: background-job-tracker-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: background-job-tracker-config
    patch: |-
      - op: replace
        path: /data/DEBUG
        value: "False"
