# Generated by Django 6.0.8 on 2026-08-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("executions", "0006_executionevent"),
        ("incidents", "0002_alter_incidentevent_options_and_more"),
        ("jobs", "0003_alter_job_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_window_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Number of historical days analyzed to derive baseline metrics.",
                        verbose_name="sample window (days)",
                    ),
                ),
                (
                    "total_executions_analyzed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total executions analyzed"
                    ),
                ),
                (
                    "is_sufficient",
                    models.BooleanField(
                        default=False,
                        help_text="True if sample size is sufficient to establish a statistically valid baseline.",
                        verbose_name="is sufficient",
                    ),
                ),
                (
                    "avg_interval_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="average interval (seconds)"
                    ),
                ),
                (
                    "median_interval_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="median interval (seconds)"
                    ),
                ),
                (
                    "min_interval_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="minimum interval (seconds)"
                    ),
                ),
                (
                    "max_interval_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="maximum interval (seconds)"
                    ),
                ),
                (
                    "avg_runtime_ms",
                    models.FloatField(blank=True, null=True, verbose_name="average runtime (ms)"),
                ),
                (
                    "p50_runtime_ms",
                    models.FloatField(blank=True, null=True, verbose_name="p50 runtime (ms)"),
                ),
                (
                    "p95_runtime_ms",
                    models.FloatField(blank=True, null=True, verbose_name="p95 runtime (ms)"),
                ),
                (
                    "p99_runtime_ms",
                    models.FloatField(blank=True, null=True, verbose_name="p99 runtime (ms)"),
                ),
                (
                    "metrics_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="metrics summary"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="calculated at"),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job baseline",
                "verbose_name_plural": "job baselines",
            },
        ),
        migrations.CreateModel(
            name="JobExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_interval_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected cadence/interval between job executions in seconds.",
                        null=True,
                        verbose_name="expected interval (seconds)",
                    ),
                ),
                (
                    "max_runtime_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum runtime before a running execution is considered stalled.",
                        null=True,
                        verbose_name="maximum runtime (seconds)",
                    ),
                ),
                (
                    "grace_period_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Buffer seconds added to expected interval before declaring a missed execution.",
                        verbose_name="grace period (seconds)",
                    ),
                ),
                (
                    "max_queue_delay_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Maximum seconds an execution can remain pending in queue before considered overdue.",
                        verbose_name="maximum queue delay (seconds)",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether reliability evaluation is enabled for this job.",
                        verbose_name="is enabled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expectation",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job expectation",
                "verbose_name_plural": "job expectations",
            },
        ),
        migrations.CreateModel(
            name="ReliabilityFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("MISSED_EXECUTION", "Missed Execution"),
                            ("STALLED_EXECUTION", "Stalled Execution"),
                            ("OVERDUE_EXECUTION", "Overdue Execution"),
                        ],
                        max_length=30,
                        verbose_name="condition type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RECOVERED", "Recovered")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("DEGRADED", "Degraded"), ("CRITICAL", "Critical")],
                        default="DEGRADED",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata snapshot of observed values and evaluation details.",
                        verbose_name="details",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="detected at"),
                ),
                (
                    "recovered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="recovered at"),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last evaluated at"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific execution that stalled or became overdue, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reliability_findings",
                        to="executions.execution",
                        verbose_name="execution",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reliability_findings",
                        to="incidents.incident",
                        verbose_name="incident",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_findings",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "reliability finding",
                "verbose_name_plural": "reliability findings",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(fields=["job", "status"], name="reliability_job_id_88238d_idx"),
                    models.Index(
                        fields=["condition_type", "status"],
                        name="reliability_conditi_c86876_idx",
                    ),
                    models.Index(fields=["detected_at"], name="reliability_detecte_7c05c8_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("execution__isnull", True), ("status", "ACTIVE")),
                        fields=("job", "condition_type"),
                        name="unique_active_job_level_finding",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("execution__isnull", False), ("status", "ACTIVE")),
                        fields=("job", "condition_type", "execution"),
                        name="unique_active_execution_level_finding",
                    ),
                ],
            },
        ),
    ]
