# Generated by Django 6.0.8 on 2026-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reliability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobbaseline",
            name="avg_hourly_volume",
            field=models.FloatField(blank=True, null=True, verbose_name="average hourly volume"),
        ),
        migrations.AddField(
            model_name="jobbaseline",
            name="failure_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="failure rate (%)"),
        ),
        migrations.AddField(
            model_name="jobbaseline",
            name="retry_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="retry rate (%)"),
        ),
        migrations.AlterField(
            model_name="reliabilityfinding",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("MISSED_EXECUTION", "Missed Execution"),
                    ("STALLED_EXECUTION", "Stalled Execution"),
                    ("OVERDUE_EXECUTION", "Overdue Execution"),
                    ("FAILURE_RATE_ANOMALY", "Failure Rate Anomaly"),
                    ("RETRY_RATE_ANOMALY", "Retry Rate Anomaly"),
                    ("DURATION_ANOMALY", "Duration Anomaly"),
                    ("EXECUTION_VOLUME_ANOMALY", "Execution Volume Anomaly"),
                ],
                max_length=30,
                verbose_name="condition type",
            ),
        ),
    ]
