"""Serializers for AI Reliability Assistant requests and responses."""

from rest_framework import serializers


class AIInvestigationRequestSerializer(serializers.Serializer):
    """Serializer for incoming incident AI investigation questions."""

    question = serializers.CharField(
        required=True,
        min_length=1,
        max_length=1000,
        trim_whitespace=True,
        help_text="User question about the incident (e.g. 'Why did this incident happen?').",
    )


class AIEvidenceItemSerializer(serializers.Serializer):
    """Serializer for individual evidence items grounding AI claims."""

    source = serializers.ChoiceField(
        choices=[
            "incident",
            "incident_event",
            "analytics",
            "reliability",
            "incident_intelligence",
            "runbook",
            "postmortem",
            "execution",
        ],
        help_text="Category of BJT telemetry or domain artifact.",
    )
    reference_id = serializers.CharField(
        max_length=255,
        allow_blank=True,
        default="",
        help_text="Identifier of the entity or metric (e.g. 'INC-42', 'job-12', 'EVT-101').",
    )
    fact = serializers.CharField(
        help_text="Observed factual telemetry or confirmed event detail.",
    )


class AIRecommendationItemSerializer(serializers.Serializer):
    """Serializer for actionable recommendations generated by AI."""

    action = serializers.CharField(
        help_text="Recommended operational action or investigation path.",
    )
    reason = serializers.CharField(
        help_text="Grounding reason tied to observed facts.",
    )


class AIInvestigationResponseSerializer(serializers.Serializer):
    """Serializer for complete AI investigation response payload."""

    answer = serializers.CharField(
        help_text="Coherent markdown answer grounded strictly in supplied telemetry.",
    )
    confidence = serializers.ChoiceField(
        choices=["HIGH", "MEDIUM", "LOW", "INSUFFICIENT_EVIDENCE"],
        help_text="Estimated confidence level based on telemetry completeness.",
    )
    evidence = AIEvidenceItemSerializer(
        many=True,
        default=list,
        help_text="List of empirical facts grounding the response.",
    )
    recommendations = AIRecommendationItemSerializer(
        many=True,
        default=list,
        help_text="Actionable suggestions for human operators.",
    )
