# Generated by Django 6.0.8 on 2026-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCreationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_teams_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum active teams a user can create/own. Leave blank for unlimited.",
                        null=True,
                        verbose_name="max teams per user",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "team creation setting",
                "verbose_name_plural": "team creation settings",
            },
        ),
    ]
