# Generated by Django 6.0.8 on 2026-08-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("jobs", "0001_initial"),
        ("projects", "0005_alter_apikey_options"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("DEGRADED", "Degraded"), ("CRITICAL", "Critical")],
                        default="DEGRADED",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="assigned at"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="acknowledged at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolved at"),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[("MANUAL", "Manual"), ("AUTOMATIC", "Automatic")],
                        max_length=20,
                        null=True,
                        verbose_name="resolution type",
                    ),
                ),
                (
                    "trigger_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata about the metric values that triggered this incident.",
                        verbose_name="trigger metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="alerts.alertrule",
                        verbose_name="alert rule",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_assigned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to="teams.teammember",
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "incident",
                "verbose_name_plural": "incidents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("ASSIGNED", "Assigned"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("NOTE_ADDED", "Note Added"),
                            ("REOPENED", "Reopened"),
                            ("AUTO_RESOLVED", "Automatically Resolved"),
                            ("MANUALLY_RESOLVED", "Manually Resolved"),
                        ],
                        max_length=30,
                        verbose_name="event type",
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="event time"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "incident event",
                "verbose_name_plural": "incident events",
                "ordering": ["event_time"],
            },
        ),
        migrations.CreateModel(
            name="IncidentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "incident note",
                "verbose_name_plural": "incident notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["OPEN", "ACKNOWLEDGED"])),
                fields=("alert_rule", "project", "job"),
                name="unique_active_incident_with_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job__isnull", True), ("status__in", ["OPEN", "ACKNOWLEDGED"])),
                fields=("alert_rule", "project"),
                name="unique_active_incident_project_level",
            ),
        ),
    ]
