# Generated by Django 6.0.8 on 2026-08-21 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_alter_alertrule_window_minutes"),
        ("incidents", "0001_initial"),
        ("jobs", "0001_initial"),
        ("projects", "0005_alter_apikey_options"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentevent",
            options={
                "ordering": ["event_time", "id"],
                "verbose_name": "incident event",
                "verbose_name_plural": "incident events",
            },
        ),
        migrations.RemoveConstraint(
            model_name="incident",
            name="unique_active_incident_with_job",
        ),
        migrations.RemoveConstraint(
            model_name="incident",
            name="unique_active_incident_project_level",
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["project", "status"], name="incidents_i_project_c84452_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["assigned_to", "status"], name="incidents_i_assigne_f40e13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["severity", "status"], name="incidents_i_severit_1a089f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["OPEN", "ACKNOWLEDGED"]), ("job__isnull", False)
                ),
                fields=("alert_rule", "project", "job"),
                name="unique_active_incident_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["OPEN", "ACKNOWLEDGED"]), ("job__isnull", True)),
                fields=("alert_rule", "project"),
                name="unique_active_incident_per_project",
            ),
        ),
    ]
