# Generated by Django 6.0.8 on 2026-08-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_alter_incidentevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact",
                    models.JSONField(blank=True, default=dict, verbose_name="impact analysis"),
                ),
                (
                    "correlations",
                    models.JSONField(blank=True, default=list, verbose_name="correlated signals"),
                ),
                (
                    "probable_causes",
                    models.JSONField(blank=True, default=list, verbose_name="probable root causes"),
                ),
                (
                    "analysis_window_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="analysis window start"
                    ),
                ),
                (
                    "analysis_window_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="analysis window end"),
                ),
                (
                    "analysis_version",
                    models.CharField(default="1.0", max_length=20, verbose_name="analysis version"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="calculated at"),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence",
                        to="incidents.incident",
                        verbose_name="incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "incident intelligence",
                "verbose_name_plural": "incident intelligences",
                "ordering": ["-calculated_at"],
            },
        ),
    ]
