# Generated by Django 6.0.8 on 2026-08-31 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0003_incidentintelligence"),
        ("jobs", "0003_alter_job_status"),
        ("projects", "0005_alter_apikey_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentPostmortem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="root cause")),
                ("summary", models.TextField(blank=True, verbose_name="summary")),
                (
                    "timeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Human-curated timeline of events during the incident.",
                        verbose_name="timeline",
                    ),
                ),
                (
                    "what_went_well",
                    models.TextField(blank=True, verbose_name="what went well"),
                ),
                (
                    "what_went_wrong",
                    models.TextField(blank=True, verbose_name="what went wrong"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmortem",
                        to="incidents.incident",
                        verbose_name="incident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "incident postmortem",
                "verbose_name_plural": "incident postmortems",
            },
        ),
        migrations.CreateModel(
            name="PostmortemActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=1024, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmortem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="incidents.incidentpostmortem",
                    ),
                ),
            ],
            options={
                "verbose_name": "postmortem action item",
                "verbose_name_plural": "postmortem action items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Runbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MISSED_EXECUTION", "Missed Execution"),
                            ("STALLED_EXECUTION", "Stalled Execution"),
                            ("OVERDUE_EXECUTION", "Overdue Execution"),
                            ("FAILURE_RATE_ANOMALY", "Failure Rate Anomaly"),
                            ("RETRY_RATE_ANOMALY", "Retry Rate Anomaly"),
                            ("DURATION_ANOMALY", "Duration Anomaly"),
                            ("EXECUTION_VOLUME_ANOMALY", "Execution Volume Anomaly"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="trigger type",
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="List of step definitions for the runbook.",
                        verbose_name="steps",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this runbook applies specifically to this job. Must belong to the same project.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runbooks",
                        to="jobs.job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runbooks",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "runbook",
                "verbose_name_plural": "runbooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentRunbookExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "step_states",
                    models.JSONField(
                        default=dict,
                        help_text="Current status of each step, keyed by step ID.",
                        verbose_name="step states",
                    ),
                ),
                (
                    "step_history",
                    models.JSONField(
                        default=list,
                        help_text="Append-only log of step state transitions.",
                        verbose_name="step history",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runbook_executions",
                        to="incidents.incident",
                    ),
                ),
                (
                    "runbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="executions",
                        to="incidents.runbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "incident runbook execution",
                "verbose_name_plural": "incident runbook executions",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="runbook",
            index=models.Index(
                fields=["project", "is_active", "trigger_type"],
                name="incidents_r_project_ba65c0_idx",
            ),
        ),
    ]
