# Generated by Django 6.0.8 on 2026-08-31 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_incidentpostmortem_postmortemactionitem_runbook_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentpostmortem",
            name="root_cause",
        ),
        migrations.RemoveField(
            model_name="postmortemactionitem",
            name="assignee",
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="confirmed_root_cause",
            field=models.TextField(blank=True, verbose_name="confirmed root cause"),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="contributing_factors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of contributing factors identified.",
                verbose_name="contributing factors",
            ),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="impact_summary",
            field=models.TextField(blank=True, verbose_name="impact summary"),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="probable_cause",
            field=models.TextField(blank=True, verbose_name="probable cause"),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="resolution",
            field=models.TextField(blank=True, verbose_name="resolution"),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_REVIEW", "In Review"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="postmortemactionitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
        ),
        migrations.AddField(
            model_name="postmortemactionitem",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AddField(
            model_name="postmortemactionitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postmortem_action_items",
                to="teams.teammember",
            ),
        ),
        migrations.AddField(
            model_name="postmortemactionitem",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="postmortemactionitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
    ]
