# Generated by Django 6.0.8 on 2026-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_remove_incidentpostmortem_root_cause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ASSIGNED", "Assigned"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("NOTE_ADDED", "Note Added"),
                    ("REOPENED", "Reopened"),
                    ("AUTO_RESOLVED", "Automatically Resolved"),
                    ("MANUALLY_RESOLVED", "Manually Resolved"),
                    ("RUNBOOK_STARTED", "Runbook Started"),
                    ("RUNBOOK_COMPLETED", "Runbook Completed"),
                    ("RUNBOOK_CANCELLED", "Runbook Cancelled"),
                ],
                max_length=30,
                verbose_name="event type",
            ),
        ),
    ]
