# Generated by Django 6.0.8 on 2026-08-31 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_alter_incidentevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentrunbookexecution",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ASSIGNED", "Assigned"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("NOTE_ADDED", "Note Added"),
                    ("REOPENED", "Reopened"),
                    ("AUTO_RESOLVED", "Automatically Resolved"),
                    ("MANUALLY_RESOLVED", "Manually Resolved"),
                    ("RUNBOOK_STARTED", "Runbook Started"),
                    ("RUNBOOK_COMPLETED", "Runbook Completed"),
                    ("RUNBOOK_CANCELLED", "Runbook Cancelled"),
                    ("POSTMORTEM_SUBMITTED", "Postmortem Submitted"),
                    ("POSTMORTEM_COMPLETED", "Postmortem Completed"),
                ],
                max_length=30,
                verbose_name="event type",
            ),
        ),
    ]
