# Generated by Django 6.0.8 on 2026-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0007_incidentrunbookexecution_started_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runbook",
            name="trigger_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MISSED_EXECUTION", "Missed Execution"),
                    ("STALLED_EXECUTION", "Stalled Execution"),
                    ("OVERDUE_EXECUTION", "Overdue Execution"),
                    ("FAILURE_RATE", "Failure Rate"),
                    ("FAILURE_RATE_ANOMALY", "Failure Rate Anomaly"),
                    ("RETRY_RATE", "Retry Rate"),
                    ("RETRY_RATE_ANOMALY", "Retry Rate Anomaly"),
                    ("DURATION_ANOMALY", "Duration Anomaly"),
                    ("EXECUTION_VOLUME_ANOMALY", "Execution Volume Anomaly"),
                ],
                max_length=50,
                null=True,
                verbose_name="trigger type",
            ),
        ),
    ]
