# Generated by Django 6.0.8 on 2026-08-24 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_alter_incidentevent_options_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="notifications.notificationchannel",
            ),
        ),
        migrations.AddConstraint(
            model_name="inappnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "incident_event"),
                name="unique_in_app_notification",
            ),
        ),
    ]
