# Generated by Django 6.0.8 on 2026-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_alter_incidentevent_options_and_more"),
        ("notifications", "0002_alter_notificationdelivery_channel_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "last_attempt_at"],
                name="notificatio_status_95d863_idx",
            ),
        ),
    ]
