# Generated by Django 6.0.8 on 2026-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notificationdelivery_notificatio_status_95d863_idx"),
        ("projects", "0005_alter_apikey_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notificationchannel",
            constraint=models.UniqueConstraint(
                fields=("project", "type", "name"),
                name="unique_project_channel_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpolicy",
            constraint=models.UniqueConstraint(
                fields=("project", "channel", "severity"),
                name="unique_project_channel_severity_policy",
            ),
        ),
    ]
